README.md, tasks/main.yml, tests/test.yml
Also a minor improvement to clarity of the README by trying to convey hierarchy of top-level lists and the keys that exist within each item.
=> Add subsystem prefix to top-level role variables.

tasks/fs-default.yml, tasks/pool-partition-default.yml
* This was found when running a playbook where the first role instantiation created an lvm group with xfs, and the second role just changed the fs_type to ext4. The playbook would fail as the system didn't have the mkfs.ext4 executable. This means that `e2fsprogs` task was skipped in the second run-through as the registered variable `e2fsprogs_installed` was interpreted as being defined in the previous role run-through despite being skipped initially.
```yaml
---
- hosts: localhost
become: true
vars:
roles:
- name: storage
storage_pools:
- name: foo
disks: ['vdc']
volumes:
- name: test1
size: 10g
fs_type: 'xfs'
mount_point: '/opt/test1'
- name: storage
storage_pools:
- name: foo
disks: ['vdc']
volumes:
- name: test1
size: 10g
fs_type: 'ext4'
mount_point: '/opt/test1'
```
=> Need to use set_fact instead of register to track whether a package has been installed.

.lgtm.yml, library/blivet.py
LGTM defaults to Python 3 for the storage role because it was created
recently. Since it needs to support Python 2 as well, configure it
explicitly.
LGTM is a static code analyzer to identify bugs in code, it found real issues that I fixed in PR #52.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/storage/62)
=> Specify Python 2 for LGTM

README.md, defaults/main.yml, library/blivet.py, tasks/main-blivet.yml, tests/tests_change_disk_fs.yml, tests/tests_change_fs.yml, tests/tests_change_fs_use_partitions.yml, tests/tests_create_disk_then_remove.yml, tests/tests_create_lvm_pool_then_remove.yml, tests/tests_create_partition_volume_then_remove.yml, tests/tests_disk_errors.yml, tests/tests_lvm_errors.yml
This flag, `storage_safe_mode`, will prevent the implicit/automatic removal of existing file systems or device stacks. In other words, with this flag set, nothing will be removed except pools and volumes whose state is defined as `absent`.
This is related to #42
=> Add flag to prevent implicit removal of existing device/fs.

tasks/main-blivet.yml, tests/test-verify-volume-mount.yml
Some tests (like comparison) are missing in older Jinja. That makes
selectattr filter unusable on RHEL 7.
=> Replace selectattr filter with json_query filter

library/blivet.py
For consistency - other classes needed this, otherwise super() failed with Python 2 (where classic classes are the default)
=> Make remaining class new-style (derive from object)

.gitignore, .travis.yml, .travis/config.sh, .travis/custom.sh, .travis/custom_pylint.py, .travis/preinstall, .travis/runblack.sh, .travis/runcoveralls.sh, .travis/runflake8.sh, .travis/runpylint.sh, .travis/runpytest.sh, .travis/runsyspycmd.sh, .travis/runtox, .travis/utils.sh, .yamllint.yml, .yamllint_defaults.yml, ansible26_requirements.txt, custom_requirements.txt, molecule/default/Dockerfile.j2, molecule/default/molecule.yml, molecule_extra_requirements.txt, pylint_extra_requirements.txt, pylintrc, pytest26_extra_requirements.txt, pytest_extra_requirements.txt, tests/setup_module_utils.sh, tox.ini
use tox as the main task/test runner
add support for local customizations like
- no molecule test for centos6
- relaxed yamllint testing
- no flake8 or black testing
- add pytest as a dep for pylint
- setup_module_utils for unit testing
=> use tox; use latest template code

tests/tests_lvm_errors.yml
To test proper error handling the test playbook needs to attempt to create a pool that is too large for the underlying device. What is "too large" depends on the device though. We should not assume that the tests will be run against a VM with disks created by the provisioning script with the expected size, tests can be executed in any environment, like on a machine with a number of big
physical disks.
tests_lvm_errors has been using a fixed size as the "too large" size, making it fail in an environment with disks larger than that. Make it determine the size dynamically instead. The "too large" size is now just one sector more than the size of the disk that is going to be used for the test.
Reported by @yizhanglinux.
=> Determine too_large_size dynamically

tests/tests_disk_errors.yml, tests/tests_lvm_errors.yml
`ansible_failed_task` can contain unexpanded Jinja2 templates with variable references that were valid when the task failed, but not valid anymore when using the variable in the `rescue` block. In this case the problem is with task names (`.name`) that contain references to `storage_provider`. Unfortunately this completely prevents using `ansible_failed_task` even if not using the problematic attribute. Other attribute could have been used if this were not the case, like `.tags`, but until https://github.com/ansible/ansible/issues/49942 is fixed, it is better to avoid using `ansible_failed_task` and use the only other special variable describing the failed task: `ansible_failed_result`.
Eliminate the previous workaround to set storage_provider on the tasks that expand …
=> Avoid using ansible_failed_task in rescue blocks

tests/tests_disk_errors.yml, tests/tests_lvm_errors.yml
=> Avoid using ansible_failed_task in rescue blocks second round

library/blivet.py, tasks/main-blivet.yml, tests/test-verify-volume-fstab.yml, tests/test-verify-volume-mount.yml, tests/tests_swap.yml, vars/CentOS-7.yml, vars/CentOS-8.yml, vars/Fedora.yml, vars/RedHat-7.yml, vars/RedHat-8.yml
This should address #66.
It changes less than #68 did, since some of those changes were based on incorrect assertions, namely that the mount module doesn't support removing specific swap entries from /etc/fstab.
=> Correctly Manage Swap Volumes

README.md, defaults/main.yml, library/blivet.py, molecule_extra_requirements.txt, tasks/main-blivet.yml, tests/test-verify-volume-device.yml, tests/test-verify-volume-encryption.yml, tests/test-verify-volume.yml, tests/tests_luks.yml, tests/verify-role-results.yml, vars/CentOS-7.yml, vars/CentOS-8.yml, vars/Fedora.yml, vars/RedHat-7.yml, vars/RedHat-8.yml
This adds support for LUKS volumes. ~~The testing is very minimal. I'm curious what it will take to get it to pass CI.~~
=> Encrypted Volumes

README.md, defaults/main.yml, library/blivet.py, library/blockdev_info.py, tests/test-verify-pool-members.yml, tests/test-verify-pool.yml, tests/tests_luks_pool.yml, tests/verify-pool-member-crypttab.yml, tests/verify-pool-members-encryption.yml
This seems fairly complete ~~, but the tests are woefully inadequate~~ . This is on top of #90 and #100. The relevant work begins with a3293e9.
Edit: tests are reasonable now, although they don't check cipher, key size, or luks version.
=> Encrypted Pools

defaults/main.yml, library/blivet.py
__NOTE__: This will need to be rebased once the `safe_mode` changes are merged.
`Fix key for partition pool...`
This leads to a failure (crash?) any time a pool of type 'partition' is present.
`Don't unmount anything if only...`
This one is pretty self-explanatory.
`Add proper checking of specified disk...`
We already validate the supplied value of `disks` for all pools, but not for disk volumes.
`Fix passing of fs create options...`
We were incorrectly passing user-specified mkfs arguments to blivet, causing them to be ignored.
`Fail on request to resize unresizable...`
We should not silently fail if the user requests a resize of a non-resizable volume.
`Remove partitions etc as needed...`
This is _sort of_ a special-case for disk volumes, but it could be needed for other types as well. …
=> Fixes for bugs found during testing of 'missing parameters' changeset

meta/main.yml
Will also serve to rerun CI after the recent merges.
=> Update supported Fedora versions

tests/test-verify-pool-members.yml, tests/test-verify-pool.yml, tests/verify-pool-md.yml
- RAID tests now correctly acquire value to get information about RAID
- This fixes workaround that used partially hardcoded value
=> Improved RAID tests

library/blockdev_info.py, tests/test-verify-pool-volumes.yml, tests/test-verify-pool.yml, tests/test-verify-volume-encryption.yml, tests/test-verify-volume-size.yml, tests/test-verify-volume.yml
This is pretty important in general, and particularly so for resize.
A keen eye may notice the commit titled "Validate volumes within test pools". Yes, that's right: Until now we have not been validating the volumes within a pool at all. I am more astonished than you, I can assure you. Also, more embarrassed.
=> Check Volume Size in Tests

library/blivet.py, tests/tests_lvm_errors.yml, tests/tests_resize.yml
These should resolve issues with resize -- particularly when the volume has an existing file system.
Still needed:
- test validation of volume sizes
- existing resize test(s) re-enabled
=> Resize fixes

tests/tests_misc.yml
**note:** This should be merged after pull/125 merged
Add valid/invalid fs_create_options tests
'Fix passing of fs create options to blivet.'
Add unresizable test
'Fail on request to resize unresizable fs.'
Add tests for handling remove patition when setting up disk volume
'Remove partitions etc as needed when setting up disk volume.'
Add tests for mounting swap to one mount location
'Fail w/ error if mount specified w/o mountable fs.'
=> tests: add misc tests for pull/125

library/blivet.py, tests/create-test-file.yml, tests/tests_luks.yml, tests/tests_luks_pool.yml, tests/verify-data-preservation.yml
Toggling encryption is (currently) a destructive operation, and this fact is quite nonintuitive and possibly dangerous. Let it be covered by the storage_safe_mode flag, just as with other operations that cause data loss (except for explicit removal).
=> Disallow toggling encryption in safe mode

library/blivet.py, tests/tests_remove_nonexistent_pool.yml
- removing non-existent pool with underlaying disks no longer fails
=> Non-existent pool removal fix

library/blivet.py
- missing or incorrect type for volumes in storage_volumes no longer yields a confusing error message
=> Confusing error message fix

.ansible-lint, .github/workflows/tox.yml, molecule/default/molecule.yml, tests/test-verify-volume-md.yml, tests/test-verify-volume-mount.yml, tests/verify-pool-md.yml
Deprecate the use of molecule for linting.  Use tox for ansible-lint.
The next step will be to remove the ansible-lint dependency from
the molecule environments.
=> use tox for ansible-lint instead of molecule

tests/tests_deps.yml
We do not need to check the deps on localhost.  This is causing
test failures in the staging environment (which will soon become
the new production environment) due to the way we test now with
ANSIBLE_ROLES_PATH environment variable instead of the tests/roles
role symlink
=> drop localhost from tests_deps.yml

README.md, defaults/main.yml, library/blivet.py, library/find_unused_disk.py, tasks/main-blivet.yml, tests/run_blivet.yml, tests/test-verify-volume-encryption.yml, tests/tests_change_fs.yml, tests/tests_create_disk_then_remove.yml, tests/tests_create_partition_volume_then_remove.yml, tests/tests_luks.yml, tests/tests_luks_pool.yml, tests/tests_raid_pool_options.yml, tests/tests_raid_volume_options.yml, tests/verify-role-results.yml
This changes the behavior of the role such that omitted parameters do not change settings on existing pools and volumes. Omitted parameters on new pools and volumes will be given the default value, while the same on existing pools and volumes will leave whatever the current setting is intact.
=> Missing parameters

tests/run_blivet.yml, tests/tests_deps.yml
The tests_deps.yml test was using include_vars assuming the symlink
roles/linux-system-roles.storage was present.  This is deprecated.
The test was doing this in order to get the defaults and vars from
the role.  The better way to do this is to use `include_role` with
the `public: true` parameter so that the role will expose its private
variables to the play.
=> remove include_vars, use public: true to export role vars, defaults

README.md, library/blivet.py, tests/tests_create_lv_size_equal_to_vg.yml, tests/tests_lvm_auto_size_cap.yml, tests/tests_lvm_errors.yml, tests/tests_misc.yml, tests/tests_resize.yml
I've included the test from #189 since it is intended to verify this change.
I am open to a discussion of whether we should expose `MAX_TRIM_PERCENT` in the role defaults. I'm also open to discussion of what the best default value is. I would definitely be open to reducing it to 2-4% as that's more in line with my intended application of this.
=> Trim volume size as needed to fit in pool free space

library/blivet.py
BlivetVolume._get_device_id is only used to look up pre-existing
volumes, so we don't have to try too hard to guess it by name.
We can just see if the disk has a single partition and, if so,
return the name of that partition.
Fixes: #141
=> Be smarter in choosing expected partition name.

library/blivet.py, tests/tests_missing_volume_type_in_pool.yml
The operations performed were already correct, but the `blivet` module's return value showed the wrong type for the volume.
=> Capture inherited volume type in return value.

tests/test-verify-volume-size.yml
This should prevent spurious test failures due to metadata or partition alignment.
=> Allow a tolerance of up to 1% when verifying volume size in tests.

tests/tests_create_lvmvdo_then_remove.yml
https://bugzilla.redhat.com/show_bug.cgi?id=1991062
Am getting this error when testing vdo:
```
Failed to commit changes to disk: Process reported exit code 3: modprobe: FATAL: Module dm-vdo not found in directory /lib/modules/5.14.0-0.rc4.35.el9.x86_64
/usr/sbin/modprobe failed: 1
vdo: Required device-mapper target(s) not detected in your kernel.
Run `lvcreate --help' for more information.
```
So I'll just skip vdo testing unless both kvdo and dm-vdo are found.
=> skip test if kvdo and dm-vdo are not found

tests/tests_lvm_errors.yml
https://bugzilla.redhat.com/show_bug.cgi?id=1990793
The test was using `volume_size`, which is undefined, instead
of `volume1_size`.  Furthermore, the error was being masked by
the `rescue` block because the rescue was not checking for the
correct error message.  The fix is to use `volume1_size` AND check
for the correct error message.
I'll note that there are several tests that do not look for the
correct error message, and we may run into this problem with other
tests.
=> use volume1_size; check for expected error

tasks/main-blivet.yml
Crypttab is not available in ansible-core, hence need to replace it
=> Replace crypttab with lineinfile

tests/tests_change_fs.yml, tests/tests_change_fs_use_partitions.yml, tests/tests_change_mount.yml, tests/tests_create_lv_size_equal_to_vg.yml, tests/tests_create_lvm_pool_then_remove.yml, tests/tests_create_lvmvdo_then_remove.yml, tests/tests_create_raid_pool_then_remove.yml, tests/tests_disk_errors.yml, tests/tests_existing_lvm_pool.yml, tests/tests_fatals_raid_pool.yml, tests/tests_luks.yml, tests/tests_luks_pool.yml, tests/tests_lvm_auto_size_cap.yml, tests/tests_lvm_errors.yml, tests/tests_lvm_multiple_disks_multiple_volumes.yml, tests/tests_lvm_one_disk_multiple_volumes.yml, tests/tests_lvm_one_disk_one_volume.yml, tests/tests_lvm_percent_size.yml, tests/tests_misc.yml, tests/tests_null_raid_pool.yml, tests/tests_raid_pool_options.yml, tests/tests_remove_mount.yml, tests/tests_remove_nonexistent_pool.yml, tests/tests_resize.yml
lvm is currently broken on el9.  We need to skip these tests until
lvm is fixed.  See https://bugzilla.redhat.com/show_bug.cgi?id=1967212
=> add tags to allow skipping lvm tests

.github/workflows/tox.yml
py27 is no longer supported
See https://github.com/linux-system-roles/linux-system-roles.github.io/issues/70
for more details
=> [citest skip] remove py27 from github CI testing

README.md, tasks/main-blivet.yml
On some platforms, udev is not updated immediately after blivet
completes its disk operations.  The user can set
`storage_udevadm_trigger: true` in order to cause udev to ensure
those changes take effect immediately.
=> add support for storage_udevadm_trigger

README-devel.md, README.md, library/blivet.py, tests/test-verify-pool-members.yml, tests/test-verify-volume-mount.yml, tests/tests_create_raid_pool_then_remove.yml, tests/verify-pool-member-lvmraid.yml, tests/verify-pool-members-lvmraid.yml
- raid_level can be used on pool volume
- raid_disks can specify disks to be used
- test added
- refactored BlivetLVMVolume._create
- some changes to README-devel (more to come)
=> Added support for LVM RAID volumes

.sanity-ansible-ignore-2.10.txt, .sanity-ansible-ignore-2.11.txt, .sanity-ansible-ignore-2.12.txt, .sanity-ansible-ignore-2.9.txt, library/blivet.py, module_utils/storage_lsr/argument_validator.py, tests/test-verify-pool-members.yml, tests/tests_create_disk_then_remove.yml, tests/tests_create_lvmvdo_then_remove.yml, tests/tests_deps.yml, tests/tests_lvm_errors.yml
Older versions of ansible do not validate nested modules parameters for
types etc. Ansible 2.11 and newer implement this functionality. This
commit adds type definitions for nested variables.
=> Nested module params checking

library/blivet.py
These were not added after the nested parameters checks were
implemented.
=> Add LVM RAID specific parameters to module_args

tasks/set_vars.yml, tests/tests_default.yml, vars/main.yml
Allow the role to work if the playbook has set `gather_facts: false`.
The `gather_subset: min` includes all of the facts used by this
role.  Other roles may need to gather more facts.
The role gathers the facts where they are needed.  Other roles may
need to gather facts in a different place.
=> allow role to work with gather_facts: false

library/blivet.py, tests/test-verify-volume-fstab.yml, tests/tests_misc.yml
When support for argument validation was added, that support did not
include the `mount_options` parameter.  This fix adds back that
parameter.  In addition, the volume module arguments are refactored
so that the common volume parameters such as `mount_options` can be
specified in one place.
This adds a test for the `mount_options` parameter, and adds
verification for that parameter.
=> add support for mount_options

defaults/main.yml, library/blivet.py, module_utils/storage_lsr/argument_validator.py, tests/test-verify-pool-members.yml, tests/tests_create_thinp_then_remove.yml, tests/verify-pool-member-thin.yml, tests/verify-pool-members-thin.yml
Storage role support for thin provisioning.
Volumes under LVM pool now can use three new options:
- 'thin' - type bool
- setting to True puts the volume into a thin pool
- 'thin_pool_name' - type str
- specifies the name of the thin pool for this volume
- selects thin pool with the same name if it exists
- tries to create new thin pool if it does not
- if omitted and no existing thin pool is present, the name is generated automatically
- if omitted and exactly one thin pool is present, the volume is put into existing thin pool
- if omitted and more than one thin pool is present, exception is raised
- 'thin_pool_size' - type Size
- specifeis size of the thin pool
=> Thin pool support

README.md, library/blivet.py, tests/tests_create_raid_pool_then_remove.yml
Intended replacement for #271 
We can trick blivet to support raid0 for LVM RAID with just a small change in the role. I've also tried to make the supported levels in README less confusing.
=> LVM RAID raid0 level support

library/blivet.py, tests/tests_create_lvm_cache_then_remove.yml
Fixes: #252
Note: The tests will now fail everywhere for now because the blivet with support for cache creation is not yet released. I'll make sure to properly skip the test on systems with old blivet when I know which version(s) supports it on RHEL and Fedora.
=> Add support for attaching LVM cache to existing LVs

tests/tests_lvm_pool_members.yml
Multiple bugs in blivet were fixed in order to make the feature
work and without the correct version even the most basic test to
remove a PV from a VG will fail so we should skip the entire test
with old versions of blivet.
----
I originally skipped only the last test case with a logical volume in the VG, but one of the blivet issues also prevents removing a PV from a VG so basically all the tests will fail with older versions of blivet.
=> Skip the entire test_lvm_pool_members playbook with old blivet

tests/verify-role-results.yml
If you use
```yaml
loop_control:
loop_var: storage_test_pool
```
Then the variable `storage_test_pool` is scoped local to the task
and is undefined after the task.  In addition, referencing the
variable after the loop causes this warning:
```
[WARNING]: The loop variable 'storage_test_pool' is already in use. You should
set the `loop_var` value in the `loop_control` option for the task to something
else to avoid variable collisions and unexpected behavior.
```
=> loop variables are scoped local - no need to reset them

CHANGELOG.md
[1.9.0] - 2022-07-19
- Add support for attaching LVM cache to existing LVs (#273)
Fixes: #252
- Add support for managing pool members (#264)
For LVM pools this adds support for adding and removing members
(PVs) from the pool (VG).
* Do not allow removing members from existing pools in safe mode
- loop variables are scoped local - no need to reset them (#282)
If you use
```yaml
loop_control:
loop_var: storage_test_pool
```
Then the variable `storage_test_pool` is scoped local to the task
and is undefined after the task.  In addition, referencing the
variable after the loop causes this warning:
```
[WARNING]: The loop variable 'storage_test_pool' is already in use. You should
set the `loop_var` value in the `loop_control` option for the task to something
else to avoid …
```
=> Version 1.9.0 - CHANGELOG.md [citest skip]

.github/workflows/changelog_to_tag.yml
Use GITHUB_REF_NAME for the push branch name if main or master,
otherwise use other methods.  Fix a bug with using git branch -r
to ignore errors if branch did not match pattern.
=> Use GITHUB_REF_NAME if main or master [citest skip]

tests/tests_create_raid_pool_then_remove.yml, tests/tests_create_raid_volume_then_remove.yml, tests/tests_fatals_raid_pool.yml, tests/tests_fatals_raid_volume.yml, tests/tests_null_raid_pool.yml, tests/tests_swap.yml
Creating raid will be failed if we don't have enough unused disks, set disks_needed earlier.
=> Add disks_needed for raid test cases

tests/tests_lvm_pool_members.yml
Do not use `end_play` with the conditional `when` which uses variables
for the condition.  The problem is that `end_play` is executed in a
different scope where the variables are not defined, even when using
`set_fact`.  The fix is to instead use a `block` and a `when`.
=> use block instead of end_play

CHANGELOG.md
[1.9.2] - 2022-11-01
- none
- Master thin support size fix (#299)
Fixed calculation of relative thinp sizes
- percent specified 'size' of thin pool volume is now properly
calculated from size of parent thinpool
Fixed size and percentage handling for thin pools
- percentage size thin volume now correctly references its parent device
for size calculation
- percentage values are now accepted size for thin pool size
- Add disks_needed for raid test cases (#300)
Creating raid will be failed if we don't have enough unused disks, set
disks_needed earlier.
Set disks_needed=2 for tests_swap.yml
- use block instead of end_play (#302)
Do not use `end_play` with the conditional `when` which uses variables
for the condition.  The problem is that `end_play` is executed in a …
=> Version 1.9.2 - CHANGELOG.md [citest skip]

tests/provision.fmf, tests/test-verify-volume-size.yml
- fixed size calculation for large size thin pools in the test
- modified provision.fmf disk size to simulate larger disks in the tests
=> Thin pool test with large size volume fix

tests/test-verify-volume-size.yml
There seems to be an issue calculating the expected size and the
actual size of the volume.  On some systems, the difference is
greater than 1% but less than 2%.  We are working on a better, more
reliable method of calculating the expected and actual sizes.  In
the meantime, make the threshold 2%.
=> Use a threshold of 2 percent in volume size check

CHANGELOG.md
[1.9.4] - 2022-12-16
- none
- none
- Tests - use a threshold of 2 percent in volume size check (#313)
There seems to be an issue calculating the expected size and the
actual size of the volume.  On some systems, the difference is
greater than 1% but less than 2%.  We are working on a better, more
reliable method of calculating the expected and actual sizes.  In
the meantime, make the threshold 2%.
=> Version 1.9.4 - CHANGELOG.md [citest skip]

tests/tests_lvm_pool_members.yml
In case "--skip-tags tests::nvme" is set when running ansible, tests_lvm_pool_members_nvme_generated.yml is not "executed", but the values and the conditions are evaluated. Then, since ansible_facts are not set by the setup module, the variables is_fedora, is_rhel?, and blivet_pkg_version are left undefined, which causes an error in the "when" condition with "'is_fedora' is undefined".
To workaround it, we should check if at least one of the variables is defined before evaluating them.
=> Improve skip tags handling in the tests_lvm_pool_members tests

library/resolve_blockdev.py
library/resolve_blockdev.py
- File is opened but is not closed.
Additional fix based on the comment by @richm:
https://github.com/linux-system-roles/storage/pull/329#issuecomment-1409087501
Thanks!
=> Fix issues found by CodeQL

library/find_unused_disk.py, tests/get_unused_disk.yml, tests/tests_misc.yml, tests/tests_swap.yml
On EL7 the swap size must be less than 128GB, so change the tests
to restrict the size.  This required introducing a `max_size` parameter
to find_unused_disk.
I also took this opportunity to do some ansible-lint 6.x cleanup
for the code I touched.  There is still a huge amount of tests/
code that is not ansible-lint 6.x clean.
=> restrict swap size to less than 128GB on EL7

.github/workflows/differential-shellcheck.yml
scripts:
- tests/scripts/pre-commit
- tests/scripts/post-commit
The upstream repo for the differential shellcheck action: https://github.com/redhat-plumbers-in-action/differential-shellcheck
=> Use custom shellcheck github action

README.md, library/blivet.py, tasks/main-blivet.yml, tests/test-verify-volume-mount.yml, tests/tests_create_disk_then_remove.yml
Added new volume options related to mount point directory: mount_user - directory owner (string)
mount_group - directory group (string)
mount_permissions - directory permissions (string; same format as chmod)
Resolves: rhbz#2181661
=> feat: User-specified mount point owner and permissions

library/blivet.py, tests/test-verify-volume-md.yml, tests/tests_raid_pool_options.yml, tests/tests_raid_volume_options.yml, tests/verify-pool-md.yml
Looks like we forgot `raid_chunk_size` when adding the pool/volume parameters checking.
=> fix: Allow using raid_chunk_size for RAID pools and volumes

tests/tests_luks.yml, tests/tests_luks_pool.yml
Can test with FIPS by setting the environment variable
`SYSTEM_ROLES_TEST_FIPS=true` before running the LUKS tests.
Can set the LUKS cipher with `SYSTEM_ROLES_LUKS_CIPHER` - the
default is `aes-xts-plain64`
=> test: enable FIPS testing; configurable LUKS cipher

README.md, defaults/main.yml, library/blivet.py, tests/tests_create_raid_pool_then_remove.yml, tests/verify-pool-member-lvmraid.yml
Custom stripe size is required for SAP HANA setups.
=> feat: Add support for setting stripe size for LVM RAID

library/blivet.py, tests/tests_resize.yml
Mounted devices are now resized without unmounting them first if the filesystem supports online resizing.
Marking as draft for now, blivet support in RHEL is not yet ready.
=> feat: Add support for filesystem online resize

tests/tests_resize.yml, tests/verify-role-failed.yml
Tests are failing if storage_safe_mode is not defined in the test.
Ensure it has a default value `true`.
Also ensure that we can use a global `storage_pools` and
`storage_volumes`.
=> test: fix undefined storage_safe_mode

library/blivet.py, tests/tests_raid_volume_cleanup.yml
- raid volumes now remove existing data from member disks as needed before creation
=> fix: RAID volume pre cleanup 

vars/AlmaLinux_8.yml, vars/AlmaLinux_9.yml
Enhancement: Add full support for AlmaLinux 8 & 9. This replaces the (abandoned) pull request at https://github.com/linux-system-roles/storage/pull/211 and fixes https://github.com/linux-system-roles/storage/issues/239.
Reason: It's currently not supported.
Result: Works fine on many production systems.
=> chore: Add support for AlmaLinux 8 & 9

library/blivet.py
Enhancement: The role is not idempotent if the system has swap. At every execution, the swap entries are remove and re-added in the next task.
Reason: There is specific code that deletes swap unconditionally. I could not find any apparent real reason for this piece of code to exist.
Result: Role is idempotent.
=> fix: Do not remove swap at every run

README.md, library/blivet.py, tests/test-verify-volume-fs.yml, tests/tests_change_fs.yml
Currently whenever volume is created without fs_type specification, a filesystem of default type (i.e. xfs) is automatically put on it.
This change allows user to prevent FS creation by using "unformatted" value as a fs_type option. In the same manner it also allows to remove an existing FS. To be able to do that the safe mode has to be off.
Enhancement:
Reason:
Result:
Issue Tracker Tickets (Jira or BZ if any):
=> feat: Support for creating volumes without a FS

.ostree/get_ostree_data.sh, meta/collection-requirements.yml, tasks/enable_coprs.yml, tasks/main-blivet.yml, tasks/set_vars.yml, tests/get_unused_disk.yml, tests/test-verify-volume-encryption.yml, tests/test-verify-volume-mount.yml, tests/tests_luks.yml, tests/tests_luks_pool.yml, tests/tests_lvm_auto_size_cap.yml, tests/tests_safe_mode_check.yml, tests/verify-pool-member-encryption.yml
The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …
=> refactor: improve support for ostree systems

tests/tests_lvm_pool_shared.yml
Save and restore lvm.conf
Put the test in a `block`, and put all of the cleanup in `always`.
=> test: Ensure lvm pool shared test cleanup

library/blivet.py, tests/test-verify-volume-fs.yml, tests/tests_lvm_pool_shared.yml, tests/tests_volume_relabel.yml
GFS2 is supported by blivet, but the support is disabled by default so we need to enable it.
Fixes: #417
=> feat: Enable GFS2 support in blivet

tests/test-verify-volume-size.yml
QE reported a test failure like this:
```
TASK [Show actual size] ********************************************************
ok: [localhost] => {
"storage_test_actual_size": {
"bytes": 1649267441664,
"changed": false,
"failed": false,
"lvm": "1t",
"parted": "1TiB",
"size": "1 TiB"
}
}
TASK [Show expected size] ******************************************************
ok: [localhost] => {
"storage_test_expected_size": "1600321314816"
}
TASK [Assert expected size is actual size] *************************************
fatal: [localhost]: FAILED! => {
"assertion": "(storage_test_expected_size | int - storage_test_actual_size.bytes) | abs / storage_test_expected_size | int < 0.02",
"changed": false,
"evaluated_to": false,
"msg": "Volume test1 has unexpected size (expected: 1600321314816 / actual: …
```
=> test: disk size is ok if less than 4 percent of expected

tests/tests_lvm_pool_shared.yml
Our CI and local test frameworks do not currently support the
shared lvm pool test.  Skip it by default.
If you want to run the test, set the environment variable
`SYSTEM_ROLES_STORAGE_SHARED_TEST=true` in your
`ansible-playbook` invocation environment e.g.
`SYSTEM_ROLES_STORAGE_SHARED_TEST=true ansible-playbook ... tests_lvm_pool_shared.yml`
=> test: skip lvm pool shared test if not supported

tests/tests_create_lv_size_equal_to_vg.yml, tests/tests_misc.yml, tests/tests_resize.yml
Device sizes specified in sectors are in general in 512 sectors regardless of the actual device physical sector size. Example of ansible_devices facts for a 4k sector size drive:
...
"sectors": "41943040",
"sectorsize": "4096",
"size": "20.00 GB"
...
Resolves: RHEL-30959
=> test: fix sector-based disk size calculation from ansible_devices

library/blivet.py, tests/tests_volume_relabel.yml
Formats like LUKS or LVMPV don't support labels so we need to skip
the label check in BlivetVolume._reformat.
Resolves: RHEL-29874
(The second commit is just partially related to this, I found that issue when testing with LUKS which also doesn't have label support in blivet.)
=> fix: Fix recreate check for formats without labelling support

library/find_unused_disk.py, tests/get_unused_disk.yml, tests/tests_change_fs_use_partitions.yml, tests/tests_create_lvm_cache_then_remove.yml, tests/tests_create_thinp_then_remove.yml, tests/tests_fatals_cache_volume.yml, tests/tests_lvm_multiple_disks_multiple_volumes.yml, tests/tests_lvm_pool_members.yml, tests/unit/test_unused_disk.py
LVM doesn't allow creating VGs on top of disks with different sector sizes and when running our tests on machine with disks with both 512 and 4096 sectors LVM tests that use multiple disks can fail. This change adds a new option to the find_unused_disks module to request disks with the same sector sizes and uses this new option in the LVM tests that use multiple disks.
Issue Tracker Tickets (Jira or BZ if any): RHEL-25994
=> fix: Get same sector size disks for multi device LVM tests

library/blivet.py
Latest pylint added a new check for values used before assignment. This fixes these issues found in the blivet module. Some of these are false positives, some real potential issues.
=> fix: Fix 'possibly-used-before-assignment' pylint issues

tests/tests_lvm_pool_members.yml
tests_lvm_pool_members started to fail. It tried to create a device with a requested size (20m) that was less than minimal allowed size (300m) for that type of volume. Role automatically resized the device to allowed size. That lead to discrepancy in actual and expected size values.
Increasing the requested device size to be same or larger than minimal fixes the issue.
=> test: lvm pool members test fix

tests/tests_misc.yml
Different versions of blivet return a different error message when trying to create a filesystem with invalid parameters.
On Fedora 39 and older:
"Failed to commit changes to disk: (FSError('format failed: 1'), '/dev/mapper/foo-test1')"
On Fedora 40 and newer:
"Failed to commit changes to disk: Process reported exit code 1: mke2fs: invalid block size - 512\n"
=> fix: Fix expected error message in tests_misc.yml

README.md, library/blivet.py, library/blockdev_info.py, tests/test-verify-pool-members.yml, tests/test-verify-volume-fs.yml, tests/test-verify-volume-mount.yml, tests/tests_stratis.yml, tests/verify-pool-stratis.yml, vars/AlmaLinux_8.yml, vars/AlmaLinux_9.yml, vars/CentOS_8.yml, vars/CentOS_9.yml, vars/Fedora.yml, vars/RedHat_8.yml, vars/RedHat_9.yml, vars/Rocky_8.yml, vars/Rocky_9.yml
Support for creating and managing Stratis pools and volumes. For now this is just a draft because we need a new version of Blivet to be available for the full support. This includes support for creating Stratis pools and filesystems and adding new block devices to an existing Stratis pool (removing block devices is not supported by Stratis). Encrypted Stratis pools can be created with Clevis/Tang or TPM support.
Resolves: RHEL-31854
=> feat: Stratis support

README.md, defaults/main.yml, library/blivet.py, tests/scripts/does_library_support.py, tests/test-verify-pool-members.yml, tests/tests_lvm_pool_pv_grow.yml, tests/verify-pool-member-pvsize.yml
There is an usecase when the physical device size can change (e.g. on
VM). We need to be able to change the size of the LVM PV to accomodate
that. This adds a new pool parameter `grow_to_fill`. When set, pool PVs
will try to take all available space on their respective devices.
Defaults to `False`.
Requires blivet version that supports this feature.
For tests this is checked by using `does_library_support` script.
Storage role development often relies on blivet library and changes in
it. Whether or not is specific feature supported by blivet is usually determined
by blivet version. That is a cumbersome process, especially when the feature
has not yet been added into blivet and the version has to be guessed.
Added script `does_library_support` verifies existence of the feature by using …
=> feat: PV resize support

README.md
Missing information about Stratis support, default value for `grow_to_fill`, notes about pool type-specific arguments etc.
Resolves: https://github.com/linux-system-roles/storage/issues/455
Resolves: https://github.com/linux-system-roles/storage/issues/428
Resolves: https://github.com/linux-system-roles/storage/issues/385
Related: https://github.com/linux-system-roles/storage/issues/437
=> docs: Fix multiple small issues in README.md

tasks/main-blivet.yml, tests/test-verify-volume-fstab.yml
Feature: Write storage role fingerprint to /etc/fstab
Reason: This will allow us to track usage of the storage role
on managed nodes.
Result: Storage role usage on managed nodes can be tracked.
=> feat: write storage role fingerprint to /etc/fstab

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.18.0
=> docs(changelog): version 1.18.0 [citest skip]

library/blivet.py, tests/tests_lvm_pool_members.yml
When removing a PV from a VG we currently remove only the PV partition and not the partition table on the disk. This fixes this by removing the partition table too.
=> fix: Remove partition table from disk removed from a VG

vars/AlmaLinux_10.yml, vars/AlmaLinux_8.yml, vars/AlmaLinux_9.yml, vars/CentOS_10.yml, vars/CentOS_7.yml, vars/CentOS_8.yml, vars/CentOS_9.yml, vars/Fedora.yml, vars/RedHat_10.yml, vars/RedHat_7.yml, vars/RedHat_8.yml, vars/RedHat_9.yml, vars/Rocky_8.yml, vars/Rocky_9.yml
The s390 plugin is needed everywhere but on s390 only (it is not available on other architectures). The filesystem plugin is needed only on Fedora and CentOS/RHEL 10.
=> fix: Add libblockdev s390 and FS plugins to blivet dependencies list

vars/OracleLinux_9.yml
Enhancement: adding support for Oracle Linux 9.x
Reason: current variable files do not return a match on this OS flavor/version
Result: copied package list from RedHat_9 and verified behavior for storage_pools (lvm) backed with virtual scsi disks
Issue Tracker Tickets (Jira or BZ if any): #444
=> chore: Add support for Oracle Linux 9.x

vars/main.yml
Due to https://github.com/linux-system-roles/storage/pull/467
architecture is now a required Ansible fact
=> fix: architecture is now a required fact

tests/tests_lvm_pool_pv_grow.yml
the pvcreate call gives us problems, and different problems on different
platforms.  Use `timeout 30s` to avoid hangs when it tries
to read from stdin.  Use verbose `-vvv` to figure out why it
hangs/fails.  Use `-y` to make it not ask questions and continue
anyway.
=> test: use pvcreate with a timeout and verbose logging

.ostree/packages-runtime-CentOS-10.txt, .ostree/packages-runtime-CentOS-8.txt, .ostree/packages-runtime-CentOS-9.txt, .ostree/packages-runtime-Fedora.txt, .ostree/packages-runtime-RedHat-10.txt, .ostree/packages-runtime-RedHat-8.txt, .ostree/packages-runtime-RedHat-9.txt, .ostree/packages-testing-CentOS-10.txt, .ostree/packages-testing-CentOS-8.txt, .ostree/packages-testing-CentOS-9.txt, .ostree/packages-testing-Fedora.txt, .ostree/packages-testing-RedHat-10.txt, .ostree/packages-testing-RedHat-8.txt, .ostree/packages-testing-RedHat-9.txt, .ostree/roles-testing.txt
stratis testing needs the nbde_server role and several clevis
and tpm2 utilities.
=> fix: add stratis to list of packages for ostree

tests/tests_lvm_pool_members.yml
Older versions of lsblk cannot print the PTTYPE column.
=> fix: Use blkid instead of lsblk in tests to get partition table

README.md, tests/tests_stratis.yml
Unfortunately Blivet supports only the Stratis v3 API so we cannot support Stratis on RHEL/CentOS 8 where only Stratis v2 is available.
=> fix: Skip Stratis tests on RHEL 8 and document Stratis support

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.18.7
=> docs(changelog): version 1.18.7 [citest skip]

tests/tests_create_lvmvdo_then_remove.yml, vars/Fedora.yml, vars/RedHat_10.yml
The VDO kernel module is now part of upstream kernel and renamed from *kvdo* to *dm-vdo*. The *vdo* package with userspace tools is now available on RHEL/CentOS 10 and Fedora in standard repositories, no need to enable the Copr repository.
=> fix: VDO tests and packages fixes for Fedora and RHEL 10

tests/tests_luks.yml
The fips-mode-setup tools is being removed from RHEL. Strarting with RHEL 10 adding fips=1 to the boot cmdline is enough to enable FIPS.
=> tests: Do not 'fips-mode-setup' to enable FIPS on RHEL 10

tests/test-verify-volume-fstab.yml, tests/tests_remove_nonexistent_pool.yml
Some tests do not cause the role to touch /etc/fstab, so skip the
fingerprint check.
=> test: skip fingerprint if fstab is not written

library/blivet.py, tests/scripts/does_library_support.py, tests/test-verify-pool-members.yml, tests/tests_lvm_pool_pv_grow.yml, tests/verify-pool-member-pvsize.yml
The issues with the PV grow feature: the code doesn't correctly set the `grow_to_fill` property for blivet and uses VG size instead of the underlying block device size for the target size for the resize action. I've fixed these and adjusted tests to actually check the PV size after resize without allowing for difference bigger than 4 MiB (one physical extent for metadata and padding) and to cover the customer issue (resizing both the PV format and LV).
=> fix: Fix PV grow_to_fill feature 

.ostree/packages-runtime.txt
The packages libblockdev and libblockdev-loop are required to
build ostree images.
=> fix: ensure ostree has libblockdev and libblockdev-loop

.github/workflows/python-unit-test.yml
Ubuntu 20.04 will be removed from GH actions by April 1, 2025. We can switch to 22.04 which still has Python 2.
=> ci: Bump Ubuntu version for Python unit tests

.github/workflows/qemu-kvm-integration-tests.yml, tests/tests_lvm_pool_pv_grow.yml, tests/tests_resize.yml
This should fix the `tests_remove_mount.yml` and `tests_existing_lvm_pool.yml` follow-up failures from https://github.com/linux-system-roles/storage/pull/518#issuecomment-2803840784 . It should also make `tests_lvm_pool_pv_grow.yml` fail "correctly", i.e. with the "Unexpected difference between PV size" error (which you get when running  this in isolation), instead of the "/dev/foo: already exists in filesystem" which is due to a dirty VM.
=> tests: Fix more cleanups; ci: Attach batch.txt and batch.report on failures

tests/scripts/stratis_pool_info.py, tests/verify-pool-stratis.yml
There are multiple versions of Stratis in systems we support and it is hard to get all the information to verify test results from the Stratis cmdline utility in a consistent way. This adds a small Python script that uses Stratis DBus API to get the information we need for the tests.
=> tests: Add a custom script for getting info about Stratis pools

library/blivet.py
We need to check the size of the PV format and compare it to the size of the underlying block device when deciding if the format size should be grown. The size of the VG (self._device here) is not relevant for this operation.
This code used to work because of a bug in blivet where size of the VG was incorrectly calculated for PVs with size not matching the underlying block device size, this was fixed in blivet (see https://github.com/storaged-project/blivet/pull/1334) so the grow_to_fill feature no longer works without this fix.
Note: The blivet fix for the PV format size is now included in both Fedora and RHEL 9 and 10, but this fix is backwards compatible and should work with older blivet too.
=> fix: Correctly check PVs for grow_to_fill feature

contributing.md, plans/test_playbooks_parallel.fmf
Now that https://github.com/teemtee/tmt/pull/3128 has merged
we can use the new epel feature to enable EPEL for testing farm
=> ci: use the new epel feature to enable EPEL for testing farm
