linux-system-roles/storage

- defaults/main.yml
- tasks/fs-default.yml
- tasks/lv-default.yml
- tasks/main.yml
- tasks/mount-default.yml
- tasks/pool-default.yml
- tasks/pool-partition-default.yml
- tasks/vg-default.yml
This would also fix #4 and #7.
> Update installation tasks to speed up playbook execution

- README.md
- tests/tests_default.yml
The formatting fix of the test should improve the Galaxy score.
> Improve the YAML format of the example and of one test. Use the Galaxy prefix in README

- library/lvm_gensym.py
- library/resolve_blockdev.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linux-system-roles/storage/52)
> Fix issues found by lgtm.com

- tests/get_unused_disk.yml
- tests/tests_lvm_multiple_disks_multiple_volumes.yml
Tests used to automatically pass when not enough unused disks were found.
> Fail if there are not enough disks for testing

- library/blivet.py
- tests/run_blivet.yml
- tests/tests_deps.yml
This is an untested concept of how we can substantially reduce the amount of code we run when gathering dependencies.
> Streamline dependency gathering

- library/blivet.py
- tests/tests_disk_errors.yml
- tests/tests_lvm_errors.yml
> Check for duplicate pool/volume names.

- tests/tests_change_mount.yml
- tests/tests_lvm_multiple_disks_multiple_volumes.yml
- tests/tests_lvm_one_disk_multiple_volumes.yml
- tests/tests_remove_mount.yml
> update the indent by two spaces

- README.md
- defaults/main.yml
- library/blivet.py
- tests/provision.fmf
- tests/test-verify-volume-device.yml
- tests/test-verify-volume-fs.yml
- tests/test-verify-volume-md.yml
- tests/test-verify-volume-mount.yml
- tests/test-verify-volume.yml
- tests/tests_create_raid_volume_then_remove.yml
- tests/tests_fatals_raid_volume.yml
- tests/tests_raid_volume_options.yml
added mdraid support for volumes
added mdraid tests
> MDRAID support for volumes

- library/blivet.py
- tests/test-verify-volume-device.yml
- tests/test-verify-volume-fs.yml
- tests/test-verify-volume-mount.yml
This is an attempt to simplify the logic for checking device paths, inspired by #108.
> Simplify device path checking

- defaults/main.yml
- library/blivet.py
- tests/provision.fmf
- tests/test-verify-pool-md.yml
- tests/test-verify-pool.yml
- tests/tests_raid_pool_options.yml
- added support for additional raid pools options
- streamlined raid options handling for volumes
- added new test for raid pool options
- fixed typo in comment of existing raid test
> Advanced options support for raid pools

- library/blivet.py
- tests/test-verify-volume-fstab.yml
- tests/test-verify-volume-mount.yml
- tests/tests_swap.yml
> Don't try to set up mounts with invalid mount points.

- library/find_unused_disk.py
- tests/unit/test_unused_disk.py
> Do not report null_blk devices as unused disks.

- library/blivet.py
- moved abstract method `get_format` from `BlivetPool` to `BlivetBase`
- fixed incorrect variables in error messages
> Fix of overlooked pylint errors

- .travis/config.sh
- .travis/custom.sh
- .travis/runblack.sh
- .travis/runcoveralls.sh
- .travis/runflake8.sh
- .travis/runpylint.sh
- .travis/runpytest.sh
- .travis/runshellcheck.sh
- .travis/runsyspycmd.sh
- .travis/utils.sh
- tests/setup_module_utils.sh
- tox.ini
sync with latest template including shellcheck
fix shellcheck issues
> sync with latest template including shellcheck

- tests/tests_deps.yml
> Avoid using Jinja2 template markers in assert

- defaults/main.yml
- library/blivet.py
- tests/tests_misc.yml
This adds fixes for the luks resize bug.
> Updated version of #64

- .travis/runcollection.sh
- .travis/utils.sh
- tox.ini
- Adding .travis/runcollection.sh.
- Enabling collection as part of tox/travis tests.
> RHELPLAN-56588 - sync collections related changes from template to storage role

- library/blivet.py
- exception message when creating new LV now contains additional information
> Updated exception message

- library/blivet.py
- tests/tests_existing_lvm_pool.yml
> Look up pool by name without disk list

- .ansible-lint
- .yamllint.yml
- defaults/main.yml
- meta/main.yml
- tasks/main-blivet.yml
- tests/create-test-file.yml
- tests/get_unused_disk.yml
- tests/test-verify-pool-members.yml
- tests/test-verify-pool.yml
- tests/test-verify-volume-encryption.yml
- tests/test-verify-volume-fstab.yml
- tests/test-verify-volume-md.yml
- tests/test-verify-volume-mount.yml
- tests/tests_create_disk_then_remove.yml
- tests/tests_create_partition_volume_then_remove.yml
- tests/tests_deps.yml
- tests/tests_disk_errors.yml
- tests/tests_include_vars_from_parent.yml
- tests/tests_luks.yml
- tests/tests_luks_pool.yml
- tests/tests_lvm_auto_size_cap.yml
- tests/tests_raid_pool_options.yml
- tests/tests_raid_volume_options.yml
- tests/verify-pool-member-crypttab.yml
- Cleaning up yamllint line-length errors
- Cleaning up ansible-lint errors
> Fix issues found by linters - enable all tests on all repos - remove suppressions

- README.md
- defaults/main.yml
- library/blivet.py
- tasks/enable_copr.yml
- tasks/enable_coprs.yml
- tasks/main-blivet.yml
- tests/test-verify-pool-members.yml
- tests/tests_create_lvmvdo_then_remove.yml
- tests/verify-pool-member-vdo.yml
- tests/verify-pool-members-vdo.yml
- vars/CentOS_8.yml
- vars/Fedora.yml
- vars/RedHat_8.yml
- added support for LVM VDO
- new accepted pool options:
- vdo_compression
- vdo_deduplication
- vdo_size
- added tests for LVM VDO
> LVMVDO support

- library/blivet.py
- tests/test-verify-volume-fs.yml
- tests/tests_volume_relabel.yml
- modifying volume label no longer causes test failure
- added forced udev update which should fix occasional test failures
- added test
Fixes #99
> Fixed volume relabeling

- README.md
- library/blivet.py
- tests/test-verify-volume-size.yml
- tests/tests_lvm_percent_size.yml
We probably need to start checking volume sizes to make these tests meaningful.
> percentage-based volume size (lvm only)

- molecule_extra_requirements.txt
- tasks/main-blivet.yml
- tests/test-verify-pool-members.yml
- tests/test-verify-volume-mount.yml
This is to prepare for ansible-core, which does not support `json_query`
> replace json_query with selectattr and map

- tasks/main-blivet.yml
Set the verbosity level to 1 for all the debug operation
> Less verbosity by default

- tests/tests_include_vars_from_parent.yml
Ensure tests work when using ANSIBLE_GATHERING=explicit
> ensure role works with gather_facts: false

- CHANGELOG.md
[1.9.1] - 2022-07-26
- none
- Update README.md with latest changes (#290)
* LVM thin provisioning support.
* Support for adding/removing disks to/from existing pools.
* Cache can now be attached to an pre-existing volume.
Fixes: #287
Fixes: #288
Fixes: #289
- changelog_to_tag action - support other than "master" for the main branch name, as well (#291)
> Version 1.9.1 - CHANGELOG.md [citest skip]

- tests/verify-pool-member-vdo.yml
VDO check was failing due to issue in 'vdostats'.
Modified vdo testing so 'lvs' is used to get data instead
> Modified lvmvdo check

- CHANGELOG.md
[1.9.5] - 2023-01-19
- none
- none
- ansible-lint 6.x fixes (#317)
- Improve skip tags handling in the tests_lvm_pool_members tests (#319)
> Version 1.9.5 - CHANGELOG.md [citest skip]

- CHANGELOG.md
[1.9.7] - 2023-04-06
- Fix ansible-lint issues in tests (#340)
- Add README-ansible.md to refer Ansible intro page on linux-system-roles.github.io (#342)
> Version 1.9.7 - CHANGELOG.md [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.9.8
> docs(changelog): version 1.9.8 [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.10.0
> docs(changelog): version 1.10.0 [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.11.0
> docs(changelog): version 1.11.0 [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.12.0
> docs(changelog): version 1.12.0 [citest skip]

- tests/tests_misc.yml
- tests/verify-role-failed.yml
- added missing cleanup task to the tests_misc.yml
- improved handling of safe mode in verify-role-failed.yml
Resolves: rhbz#2213691
Enhancement:
Reason:
Result:
Issue Tracker Tickets (Jira or BZ if any): rhbz#2213691 / RHELPLAN-159360
> fix: Test issue when creating fs /w invalid param

- CHANGELOG.md
Create changelog update and release for version 1.12.1
> docs(changelog): version 1.12.1 [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.12.2
> docs(changelog): version 1.12.2 [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.12.3
> docs(changelog): version 1.12.3 [citest skip]

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 1.12.4
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
> docs(changelog): version 1.12.4 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.12.5
> docs(changelog): version 1.12.5 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.15.1
> docs(changelog): version 1.15.1 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.16.1
> docs(changelog): version 1.16.1 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.16.2
> docs(changelog): version 1.16.2 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.16.3
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
> docs(changelog): version 1.16.3 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.16.4
> docs(changelog): version 1.16.4 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.16.5
> docs(changelog): version 1.16.5 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.18.1
> docs(changelog): version 1.18.1 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.18.2
> docs(changelog): version 1.18.2 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.18.5
> docs(changelog): version 1.18.5 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.18.6
> docs(changelog): version 1.18.6 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.18.8
> docs(changelog): version 1.18.8 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.18.9
> docs(changelog): version 1.18.9 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.18.10
> docs(changelog): version 1.18.10 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.18.12
> docs(changelog): version 1.18.12 [citest skip]

- .codespellrc
- .github/workflows/python-unit-test.yml
- .github/workflows/tft.yml
- plans/README-plans.md
- plans/test_playbooks_parallel.fmf
* Calculate number of managed nodes with this formula:
(( number_of_test_playbooks / 10 + 1 ))
* Add README explaining how to run the plan locally and remotely
> ci: Add test plan that runs CI tests and customize it for each role

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 1.18.13
> docs(changelog): version 1.18.13 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.18.14
> docs(changelog): version 1.18.14 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.18.15
> docs(changelog): version 1.18.15 [citest skip]
